language: emacs-lisp
before_install:
  - git submodule update --init
  - sudo apt-get install -qq python-setuptools
  - sudo easy_install pyzmq
  - sudo apt-get install -qq python-virtualenv python-tornado
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
env:
  - EMACS=emacs
  - EMACS=emacs-snapshot
script:
  make travis-ci EMACS=$EMACS
